micronaut:
    application:
        name: nota-fiscal
    server:
        port: 8082
        cors:
            enabled: true

datasources:
    default:
        url: jdbc:mysql://localhost:3306/nota-fiscal
        driverClassName: com.mysql.cj.jdbc.Driver
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        username: root
        password: lazarus11

jpa:
    default:
        packages-to-scan:
            - 'notafiscal.entity'

cassandra:
    default:
        clusterName: "Invoice"
        contactPoint: "localhost"
        port: 9042
        maxSchemaAgreementWaitSeconds: 20
        ssl: false
